var DEPENDENCIAS_GOB = [
  {id:'pal1', nombre:'Secretaría del Ayuntamiento', titular:'Rodolfo Gómez Cervantes',
   dir:'Palacio Municipal s/n, Zona Centro', tel:'462 606 9999', ext:'1401',
   funcion:'administracion', funcionLabel:'Administración',
   desc:'Actas de cabildo, certificaciones y trámites oficiales del municipio.',
   lat:20.672656, lng:-101.347467, web:''},
  {id:'pal2', nombre:'Secretaría Particular del Presidente', titular:'Adriana Elizarraraz Sandoval',
   dir:'Palacio Municipal s/n, Zona Centro', tel:'462 606 9999', ext:'1101',
   funcion:'administracion', funcionLabel:'Administración',
   desc:'Oficina directa del Presidente Municipal. Audiencias y gestiones ciudadanas.',
   lat:20.672656, lng:-101.347467, web:'irapuato.gob.mx'},
  {id:'pal3', nombre:'Secretaría Técnica', titular:'Salvador Alonso Ruiz',
   dir:'Palacio Municipal s/n, Zona Centro', tel:'462 606 9999', ext:'',
   funcion:'administracion', funcionLabel:'Administración',
   desc:'Coordinación técnica de proyectos y programas municipales.',
   lat:20.672656, lng:-101.347467, web:''},
  {id:'pal4', nombre:'Comunicación Social', titular:'Brenda Rocío Orozco Torres',
   dir:'Palacio Municipal s/n, Zona Centro', tel:'462 606 9999', ext:'1130',
   funcion:'administracion', funcionLabel:'Administración',
   desc:'Información pública, prensa y comunicados oficiales del municipio.',
   lat:20.672656, lng:-101.347467, web:''},
  {id:'cg1', nombre:'Tesorería Municipal', titular:'Miguel Ángel Fonseca',
   dir:'Álvaro Obregón #100, Zona Centro — Centro de Gobierno', tel:'462 606 9999', ext:'1501',
   funcion:'finanzas', funcionLabel:'Finanzas',
   desc:'Pago de predial, licencias y adeudos municipales.',
   lat:20.672056, lng:-101.345499, web:''},
  {id:'cg2', nombre:'Contraloría Municipal', titular:'Gustavo Sánchez Guerrero',
   dir:'Álvaro Obregón #100, Zona Centro — Centro de Gobierno', tel:'462 606 9999', ext:'1701',
   funcion:'finanzas', funcionLabel:'Finanzas',
   desc:'Quejas, denuncias y fiscalización del gasto público municipal.',
   lat:20.672056, lng:-101.345499, web:''},
  {id:'cg3', nombre:'Oficialía Mayor', titular:'Ana María Flores Bello',
   dir:'Álvaro Obregón #100, Zona Centro — Centro de Gobierno', tel:'462 606 9999', ext:'1581',
   funcion:'administracion', funcionLabel:'Administración',
   desc:'Recursos humanos, nómina y administración interna municipal.',
   lat:20.672056, lng:-101.345499, web:''},
  {id:'cg4', nombre:'Dir. Tecnologías de la Información y Geomática', titular:'Jorge Alberto Wells Mendoza',
   dir:'Álvaro Obregón #100, Zona Centro — Centro de Gobierno', tel:'462 606 9999', ext:'1621',
   funcion:'administracion', funcionLabel:'Administración',
   desc:'Sistemas digitales, geomática y tecnología del municipio.',
   lat:20.672056, lng:-101.345499, web:''},
  {id:'seg1', nombre:'Secretaría de Seguridad Ciudadana Municipal', titular:'Ma. del Consuelo Cruz Galindo',
   dir:'Solidaridad 11189, Fraccionamiento CFE', tel:'462 627 3952', ext:'',
   funcion:'seguridad', funcionLabel:'Seguridad',
   desc:'Policía municipal, emergencias, denuncia ciudadana y vigilancia.',
   lat:20.692857, lng:-101.342322, web:''},
  {id:'sxx1', nombre:'Dirección de Desarrollo Urbano', titular:'Paola Berenice Frausto Reyes',
   dir:'Blvd. Solidaridad #8350 — Edificio Siglo XXI', tel:'462 635 8800', ext:'',
   funcion:'obras', funcionLabel:'Obras y Urbanismo',
   desc:'Licencias de construcción, usos de suelo y permisos de subdivisión.',
   lat:20.667872, lng:-101.328957, web:''},
  {id:'sxx2', nombre:'Dirección de Obras Públicas', titular:'Manuel Venegas Pérez',
   dir:'Blvd. Solidaridad #8350 — Edificio Siglo XXI', tel:'462 635 8800', ext:'',
   funcion:'obras', funcionLabel:'Obras y Urbanismo',
   desc:'Construcción y mantenimiento de infraestructura pública municipal.',
   lat:20.667872, lng:-101.328957, web:''},
  {id:'sxx3', nombre:'Dirección de Servicios Públicos', titular:'Rogelio Pérez Espinoza',
   dir:'Blvd. Solidaridad #8350 — Edificio Siglo XXI', tel:'462 635 8804', ext:'',
   funcion:'obras', funcionLabel:'Obras y Urbanismo',
   desc:'Alumbrado, recolección de basura, bacheo y mantenimiento urbano.',
   lat:20.667872, lng:-101.328957, web:''},
  {id:'sal1', nombre:'Dirección General de Salud', titular:'Eduardo Tovar Guerrero',
   dir:'Blvd. Lázaro Cárdenas #3247, La Moderna', tel:'462 606 9999', ext:'2032',
   funcion:'salud', funcionLabel:'Salud',
   desc:'Programas de salud pública, vacunación y atención médica municipal.',
   lat:20.681304, lng:-101.359924, web:''},
  {id:'sal2', nombre:'Sistema DIF Irapuato', titular:'Liliana del Carmen Torrero García',
   dir:'Av. Vasco de Quiroga s/n, Col. Morelos', tel:'462 626 1124', ext:'',
   funcion:'salud', funcionLabel:'Salud y Social',
   desc:'Apoyos alimentarios, adultos mayores, discapacidad y familia.',
   lat:20.657002, lng:-101.330241, web:'dif.irapuato.gob.mx'},
  {id:'sal3', nombre:'INMIRA — Instituto de las Mujeres Irapuatenses', titular:'Georgina Aboytes Guerrero',
   dir:'Francisco Sarabia 1066, Prol. La Moderna', tel:'462 627 5967', ext:'',
   funcion:'salud', funcionLabel:'Salud y Social',
   desc:'Atención a víctimas de violencia, asesoría legal y apoyo a la mujer.',
   lat:20.678172, lng:-101.363812, web:'mujeres.irapuato.gob.mx'},
  {id:'sal4', nombre:'Dirección de Desarrollo Social y Humano', titular:'Liliana Flores Rodríguez',
   dir:'Blvd. Paseo Solidaridad 11615, CFE', tel:'462 606 9999', ext:'2104',
   funcion:'salud', funcionLabel:'Salud y Social',
   desc:'Programas sociales, apoyos a comunidades y atención a vulnerables.',
   lat:20.693176, lng:-101.342115, web:''},
  {id:'sal5', nombre:'Dirección de Desarrollo Rural', titular:'Jorge Israel Lizama Ibarra',
   dir:'Blvd. Paseo Solidaridad #11615, CFE', tel:'462 606 9999', ext:'2132',
   funcion:'salud', funcionLabel:'Salud y Social',
   desc:'Apoyo a comunidades rurales, campo y desarrollo agropecuario.',
   lat:20.693153, lng:-101.342275, web:''},
  {id:'edu1', nombre:'Dirección de Educación y Juventudes', titular:'Joyce Guerrero Barajas',
   dir:'Calle Juan Álvarez #64, Zona Centro', tel:'462 606 9999', ext:'200',
   funcion:'educacion', funcionLabel:'Educación y Cultura',
   desc:'Becas, programas educativos y atención a jóvenes irapuatenses.',
   lat:20.674177, lng:-101.347952, web:''},
  {id:'edu2', nombre:'IMCAR — Casa de la Cultura', titular:'Gloria Magaly Cano de la Fuente',
   dir:'Álvaro Obregón #16, Zona Centro', tel:'462 626 8095', ext:'',
   funcion:'educacion', funcionLabel:'Educación y Cultura',
   desc:'Talleres artísticos, eventos culturales, biblioteca y exposiciones.',
   lat:20.672063, lng:-101.346458, web:'cultura.irapuato.gob.mx'},
  {id:'agua1', nombre:'JAPAMI — Agua Potable y Alcantarillado', titular:'Roberto Castañeda Tejeda',
   dir:'Prol. Torres Landa #1720, Col. Independencia', tel:'462 606 9100', ext:'',
   funcion:'servicios', funcionLabel:'Agua y Servicios',
   desc:'Tomas de agua, adeudos, reporte de fugas y alcantarillado.',
   lat:20.680238, lng:-101.346371, web:'japami.gob.mx'},
  {id:'agua2', nombre:'IMUVII — Instituto Municipal de Vivienda', titular:'Lourdes Liliana Pérez Mares',
   dir:'Av. Revolución #179 int. 105, Zona Centro', tel:'462 490 3737', ext:'',
   funcion:'servicios', funcionLabel:'Agua y Servicios',
   desc:'Créditos y apoyos para adquisición de vivienda social.',
   lat:20.674002, lng:-101.348694, web:'imuvii.gob.mx'},
  {id:'mov1', nombre:'Dirección de Movilidad y Transporte', titular:'Alfredo Torres Nohra',
   dir:'Av. Revolución #24 esq. Ramón Corona, Centro', tel:'462 215 3867', ext:'',
   funcion:'movilidad', funcionLabel:'Movilidad',
   desc:'Transporte público, permisos de circulación y control de tránsito.',
   lat:20.671517, lng:-101.348730, web:''},
  {id:'dep1', nombre:'COMUDAJ — Comisión Municipal del Deporte', titular:'Janet Estrada Ponce',
   dir:'Av. Tulipanes s/n, Col. Ciudad Deportiva', tel:'462 693 0605', ext:'',
   funcion:'deporte', funcionLabel:'Deporte y Recreación',
   desc:'Instalaciones deportivas, eventos y programas para la juventud.',
   lat:20.694335, lng:-101.376498, web:'irapuato.gob.mx/comudaj'},
  {id:'dep2', nombre:'Parque Irekua', titular:'Esther Córdoba Aguirre',
   dir:'Reverte Mexicano s/n, Viveros Revolución', tel:'462 635 1749', ext:'',
   funcion:'deporte', funcionLabel:'Deporte y Recreación',
   desc:'Parque familiar con áreas verdes, actividades recreativas y deportivas.',
   lat:20.686031, lng:-101.356258, web:''},
  {id:'plan1', nombre:'IMPLAN — Instituto Municipal de Planeación', titular:'Teresita Gallardo Arroyo',
   dir:'Blvd. Villas de Irapuato #1460, Plaza Provincia', tel:'462 625 9999', ext:'',
   funcion:'planeacion', funcionLabel:'Planeación y Economía',
   desc:'Planeación urbana, estadística y proyectos de desarrollo municipal.',
   lat:20.682801, lng:-101.380457, web:'implanirapuato.gob.mx'},
  {id:'plan2', nombre:'Dirección de Desarrollo Económico', titular:'Humberto Hernández Salgado',
   dir:'Casimiro Liceaga esq. Ramón Barreto #770', tel:'462 660 3601', ext:'',
   funcion:'planeacion', funcionLabel:'Planeación y Economía',
   desc:'Apoyo a empresas, inversión y fomento al empleo local.',
   lat:20.678885, lng:-101.360043, web:''},
  {id:'plan3', nombre:'Dir. Innovación y Gobernanza Regulatoria', titular:'Álvaro Pereira Luna',
   dir:'Blvd. Lázaro Cárdenas #3247, Col. La Moderna', tel:'462 625 5019', ext:'',
   funcion:'planeacion', funcionLabel:'Planeación y Economía',
   desc:'Simplificación de trámites e innovación gubernamental.',
   lat:20.681304, lng:-101.359924, web:''},
  {id:'plan4', nombre:'Dirección de Sustentabilidad', titular:'Gonzalo Guerrero',
   dir:'Parque Ecológico, Av. Villas de Irapuato 2278', tel:'462 606 9999', ext:'1112',
   funcion:'planeacion', funcionLabel:'Planeación y Economía',
   desc:'Medio ambiente, parques ecológicos y sustentabilidad municipal.',
   lat:20.683552, lng:-101.387539, web:''}
];

var GOB_COLORES = {
  administracion:'#00ccff', finanzas:'#ffcc00', seguridad:'#ff2255',
  obras:'#ff8800', salud:'#00ff88', educacion:'#cc88ff',
  servicios:'#44bbff', movilidad:'#ffaa00', deporte:'#00ffcc', planeacion:'#aaaaff'
};
var GOB_ICONOS = {
  administracion:'🏛️', finanzas:'💰', seguridad:'🚔', obras:'🏗️',
  salud:'🏥', educacion:'🎓', servicios:'💧', movilidad:'🚌',
  deporte:'⚽', planeacion:'📋'
};
var gobMarkers = [];
var gobFiltroActivo = 'todos';
var gobCardAbierta = null;


var DENUE_COLORS = {
  retail:'#ffcc00', serv:'#00ccff', resta:'#ff8800', mfg:'#ff4466',
  salud:'#00ff88', mayo:'#ffaa00', educ:'#cc88ff', prof:'#44aaff',
  inmob:'#88ffcc', finanz:'#ff66aa', entret:'#ff88ff', apoyo:'#aaaaff',
  gob:'#00ccff',   transp:'#ffee44', const:'#ff6600', media:'#00ffff',
  util:'#88ff44',  agro:'#88cc44',   mineria:'#888888'
};
var DENUE_LABELS = {
  retail:'🛒 Menudeo',     serv:'✂ Servicios',      resta:'🍽 Restaurantes',  mfg:'🏭 Manufactura',
  salud:'🏥 Salud',        mayo:'📦 Mayoreo',         educ:'🎓 Educación',      prof:'💼 Serv.Prof.',
  inmob:'🏠 Inmobiliaria', finanz:'🏦 Finanzas',      entret:'🎭 Entret.',      apoyo:'🔧 Apoyo',
  gob:'🏛 Gobierno',       transp:'🚛 Transporte',    const:'🏗 Construcción',  media:'📡 Medios',
  util:'⚡ Utilities',     agro:'🌱 Agro',             mineria:'⛏ Minería'
};
var DENUE_PER = ['','0-5','6-10','11-30','31-50','51-100','101-250','251+'];
